### ISSUE TITLE
Is it possible to get an example?

### ISSUE THREAD

**Issue by BigDi** [Looking4Cache/node-red-contrib-growatt#1]
I installed the node and create a configuration but how should the input message look like to call the Growatt API?
![grafik](https://user-images.githubusercontent.com/11903065/168591841-2c92fac1-2fa3-43ff-aef1-6f3ee4ddeca3.png)

**Comment by Looking4Cache** [comment]
The payload of the incomming message is not relevant. Every incomming message with any content triggers the Node to call the API.
