### ISSUE TITLE
It no longer establishes a connection.

### ISSUE THREAD

**Issue by drogon** [Looking4Cache/node-red-contrib-growatt#10]
It no longer establishes a connection.

Error: The server sent an unexpected response: /error.do?errorMess=errorNoLogin

**Comment by narfnarf123** [comment]
I can confirm that it does not work. 
But since I cannot see any data on server.growatt.com either, it could be a temporary problem with the website, not the node.

**Comment by Looking4Cache** [comment]
There was a change in the API of Growatt. The underlaying library was fixed yesterday. I jut updated it and it runs again. Will be available with V1.1.2.

**Comment by narfnarf123** [comment]
Thanks a lot. I thought you were no longer actively maintaining the node. Thanks for your effort
