### ISSUE TITLE
changes in growatt

### ISSUE THREAD

**Issue by marxus4** [Looking4Cache/node-red-contrib-growatt#2]
Hello 
It looks like there has been a change to api growatt and the node is working

**Comment by Looking4Cache** [comment]
Hi,

I dont understand the issue. If it's working, it should be fine ;)

If not, can you go deeper in the details?

**Comment by Looking4Cache** [comment]
Do you enter something in the plant ID field? If yes, if you enter it wrong, there will be a empty response from Growatt.

**Comment by marxus4** [comment]
I entered the correct data, I checked
I know that there was a problem in the home assistant integration and it
was fixed the last time it was updated
https://community.home-assistant.io/t/growatt-inverter-integration-issue/431164

czw., 23 cze 2022 o 13:07 Thorsten Heilmann ***@***.***>
napisał(a):

**Comment by Looking4Cache** [comment]
As I read the error in HA, it was based on HA core itself, not on the Growatt servers. The new URL is already entered in the library I use.

Does it shows any errors in the Node-RED logs?

**Comment by marxus4** [comment]
27 Jun 00:18:42 - [info] Starting modified nodes
27 Jun 00:18:42 - [info] Started modified nodes
27 Jun 00:18:43 - [info] [growatt:dom] marx4
27 Jun 00:18:59 - [info] Stopping modified nodes
27 Jun 00:18:59 - [info] Stopped modified nodes
27 Jun 00:18:59 - [info] Starting modified nodes
27 Jun 00:18:59 - [info] Started modified nodes
27 Jun 00:19:03 - [info] [growatt:dom] marx4
27 Jun 00:19:12 - [info] Stopping modified nodes
27 Jun 00:19:12 - [info] Stopped modified nodes
27 Jun 00:19:12 - [info] Starting modified nodes
27 Jun 00:19:12 - [info] Started modified nodes
27 Jun 00:19:13 - [info] [growatt:dom] marx4
27 Jun 00:19:26 - [info] Stopping modified nodes
27 Jun 00:19:26 - [info] Stopped modified nodes
27 Jun 00:19:26 - [info] Starting modified nodes
27 Jun 00:19:26 - [info] Started modified nodes
27 Jun 00:19:27 - [info] [growatt:dom] marx4``

**Comment by marxus4** [comment]
![growatt](https://user-images.githubusercontent.com/78980704/175836388-0ec44b36-7909-482b-aadd-7cac1ba0534b.jpg)
![growatt2](https://user-images.githubusercontent.com/78980704/175836497-bed393fa-08aa-41de-815b-65853560e58b.jpg)
I don't know if it is important but I only have one node available

**Comment by Looking4Cache** [comment]
OK, no error in the logs..

Did you tried it without any text in the plant ID field?

**Comment by marxus4** [comment]
I have tried all the combinations, I created a second empty account and it is the same and entering incorrect data gives an error

``"Error: {"result":-2,"msg":"用户名或密码错误"}"

**Comment by Looking4Cache** [comment]
Yes, this error means that the credentials are wrong.

Sorry, I don't know why the result is empty at your account. Maybe it's something inside the growatt API. Or some missing stuff in the ShineServer configurations / data.

**Comment by marxus4** [comment]
:( OK thanks

**Comment by marxus4** [comment]
https://github.com/home-assistant/core/pull/73561

czw., 23 cze 2022 o 14:26 Mariusz Krajniak ***@***.***> napisał(a):

**Comment by Looking4Cache** [comment]
I already wrote you this:
> As I read the error in HA, it was based on HA core itself, not on the Growatt servers. The new URL is already entered in the library I use.

And this:
> Yes, this error means that the credentials are wrong.
> 
> Sorry, I don't know why the result is empty at your account. Maybe it's something inside the growatt API. Or some missing stuff in the ShineServer configurations / data.

If you think that any code changes will fix that, please fork this repro and try it. Or change the files directly on your Node-RED server and try it. I released this small node that not anyone who want to access the Growatt API from Node-RED has to do it completely new. I am not able to do such a support here.
