### ISSUE TITLE
Example node-red??

### ISSUE THREAD

**Issue by mvdh02** [Looking4Cache/node-red-contrib-growatt#3]
Is it possible to put some example node-red flows in this github item? I've got a connection with the Growatt server, but the payload stays empty. A example flow with some commands will help a lot

**Comment by AlexanderJHi** [comment]
would also like help here.. i am no coder would be great to have an example to use this to get for example e-Today and how that can be made available to HomeBridge. Thanks!

**Comment by Looking4Cache** [comment]
I added the example.json to the project. This loads the data from the Growatt API as soon as the inject node is activated and prints it to the debug output. How to extract the data from the json and how to use it depends on yourself.
