### ISSUE TITLE
Change settings on Growatt 

### ISSUE THREAD

**Issue by tromanski** [Looking4Cache/node-red-contrib-growatt#5]
Hello Thorsten,

I´ve implemented your node in NodeRed to read my inverters value. This works very good! Thank you for this node. No I would like to change settings of the inverter. Is it somehow possible to change settings of the inverter with your node? I would like to change the modes e.g. Solar only (SOL) to Battery First (SBU). 

Thank you in advance for your support

**Comment by Looking4Cache** [comment]
Hi,

No. It only requests the status of the inverter/installation. Changes of parameters are not supported.

Greetings, Thorsten
