### ISSUE TITLE
Please use growatt 0.4.1

### ISSUE THREAD

**Issue by PLCHome** [Looking4Cache/node-red-contrib-growatt#6]
Please adopt the current Growatt API, the 0.2.10 is pretty buggie.
Please change in the package.json "growatt": Insert "^0.4.1" and publish a new version 1.0.1.

I just did a test install for a friend and he pulled the 2.10.

### 0.4.1: Maintenance Release

**Fixes**

- calendar structure was not always changed to timestamp

### 0.4.0: Maintenance Release

**Enhancements**

- Status data now also from TLX/TLXH

**Fixes**

- TLX Hybrid is now working
- If there are different inverters, these are now shown

### 0.3.0: Maintenance Release

**Enhancements**

- other Server over options
- Data logger settings can be called up and changed.

### 0.2.14: Maintenance Release

**Fixes**

- LINT

### 0.2.13: Maintenance Release

**Fixes**

- HEADER changed

### 0.2.12: Maintenance Release

**Fixes**

- JSON loopkiller

### 0.2.11: Maintenance Release

**Fixes**

- https rejectUnauthorized false

**Comment by Looking4Cache** [comment]
Done. Thanks for the info!
