### ISSUE TITLE
Server connect failed

### ISSUE THREAD

**Issue by do1vm** [Looking4Cache/node-red-contrib-growatt#8]
The Growatt Portal is working, but with NodeRed i get since yesterday this Message:

"Error: {"result":-5,"msg":"temporarily unavailable"}"

**Comment by Looking4Cache** [comment]
At my home it works at the moment, the Growatt server responded normally (at my location). The message indicates that there is some error on the Growatt side, not on the node.

So please try again. Also I deprecated this node, as I do not use the Growatt Shine Server system anymore.

**Comment by do1vm** [comment]
Not working for me. Is it possible to change the server in this Node? Is there a INI or config File?

server.growatt.com or server-us.growatt.com

31.7.2023, 09:51:49[node: BBS18](http://docker01:1880/#)
msg : error
"Error: {"result":-5,"msg":"temporarily unavailable"}"


Too bad that you don't use the System anymore. It will prefer to get the Data direkt from the Wifi Stick, but there is no way i think......

**Comment by Looking4Cache** [comment]
Get the data directly.. This is exactly the case why I not use the Growatt servers anymore.

https://github.com/otti/Growatt_ShineWiFi-S

With this you can flash your ShineWiFi stick with a new firmware. This firmware will output the data via MQTT and also has a REST endpoint to grab the data.

With this I update my solar data each second :)

**Comment by do1vm** [comment]
Vy cool!!!! This i try directly!
